In [14]:
# %pip install imageio

In [15]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50)

In [16]:
import imageio

img_arr = imageio.imread('../data/p1ch4/image-dog/bobby.jpg')
img_arr.shape

/var/folders/wm/znp8c4pd0r72qm3gq7rpvwn40000gn/T/ipykernel_52481/1529188539.py:3: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread('../data/p1ch4/image-dog/bobby.jpg')


(720, 1280, 3)

In [17]:
img_arr

array([[[ 77,  45,  22],
        [ 77,  45,  22],
        [ 78,  46,  21],
        ...,
        [118,  78,  52],
        [117,  77,  51],
        [116,  76,  50]],

       [[ 75,  43,  20],
        [ 76,  44,  21],
        [ 77,  45,  20],
        ...,
        [118,  78,  52],
        [117,  77,  51],
        [116,  76,  50]],

       [[ 74,  39,  17],
        [ 75,  40,  18],
        [ 77,  43,  18],
        ...,
        [117,  80,  51],
        [117,  78,  49],
        [116,  77,  48]],

       ...,

       [[215, 165,  78],
        [216, 166,  79],
        [217, 167,  80],
        ...,
        [174, 121,  51],
        [176, 123,  53],
        [176, 123,  53]],

       [[215, 165,  78],
        [216, 166,  79],
        [217, 167,  80],
        ...,
        [173, 123,  54],
        [174, 124,  55],
        [174, 124,  55]],

       [[215, 165,  78],
        [216, 166,  79],
        [217, 167,  80],
        ...,
        [159, 109,  40],
        [158, 107,  41],
        [158, 107,  41]]

In [18]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)

In [19]:
img

tensor([[[ 77,  45,  22],
         [ 77,  45,  22],
         ...,
         [117,  77,  51],
         [116,  76,  50]],

        [[ 75,  43,  20],
         [ 76,  44,  21],
         ...,
         [117,  77,  51],
         [116,  76,  50]],

        ...,

        [[215, 165,  78],
         [216, 166,  79],
         ...,
         [174, 124,  55],
         [174, 124,  55]],

        [[215, 165,  78],
         [216, 166,  79],
         ...,
         [158, 107,  41],
         [158, 107,  41]]], dtype=torch.uint8)

In [20]:
out

tensor([[[ 77,  77,  ..., 117, 116],
         [ 75,  76,  ..., 117, 116],
         ...,
         [215, 216,  ..., 174, 174],
         [215, 216,  ..., 158, 158]],

        [[ 45,  45,  ...,  77,  76],
         [ 43,  44,  ...,  77,  76],
         ...,
         [165, 166,  ..., 124, 124],
         [165, 166,  ..., 107, 107]],

        [[ 22,  22,  ...,  51,  50],
         [ 20,  21,  ...,  51,  50],
         ...,
         [ 78,  79,  ...,  55,  55],
         [ 78,  79,  ...,  41,  41]]], dtype=torch.uint8)

In [21]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [22]:
batch_size

3

In [23]:
batch

tensor([[[[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]]],


        [[[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]]],


        [[[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
       

In [26]:
import os

data_dir = '../data/p1ch4/image-cats/'
filenames = [name for name in os.listdir(data_dir)
             if os.path.splitext(name)[-1] == '.png']
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3] # <1>
    batch[i] = img_t

/var/folders/wm/znp8c4pd0r72qm3gq7rpvwn40000gn/T/ipykernel_52481/3460487691.py:7: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


In [27]:
batch

tensor([[[[156, 152,  ..., 149, 158],
          [174, 134,  ..., 136, 138],
          ...,
          [129, 130,  ..., 121, 114],
          [129, 123,  ..., 121, 120]],

         [[139, 135,  ..., 135, 147],
          [160, 119,  ..., 122, 124],
          ...,
          [111, 111,  ..., 112, 105],
          [111, 104,  ..., 110, 111]],

         [[129, 123,  ..., 132, 145],
          [155, 110,  ..., 119, 121],
          ...,
          [108, 108,  ..., 117, 110],
          [107,  98,  ..., 115, 116]]],


        [[[202, 193,  ...,  13,  12],
          [199, 192,  ...,  14,  14],
          ...,
          [ 75,  68,  ...,  36,  37],
          [ 85, 103,  ...,  37,  38]],

         [[151, 139,  ...,   9,   8],
          [151, 140,  ...,  11,  11],
          ...,
          [ 33,  26,  ...,  26,  27],
          [ 40,  58,  ...,  27,  28]],

         [[ 68,  53,  ...,   6,   5],
          [ 67,  54,  ...,   6,   6],
          ...,
          [ 11,   2,  ...,  17,  18],
          [ 19,  37,  ..

In [28]:
batch = batch.float()
batch /= 255.0

In [29]:
batch

tensor([[[[0.6118, 0.5961,  ..., 0.5843, 0.6196],
          [0.6824, 0.5255,  ..., 0.5333, 0.5412],
          ...,
          [0.5059, 0.5098,  ..., 0.4745, 0.4471],
          [0.5059, 0.4824,  ..., 0.4745, 0.4706]],

         [[0.5451, 0.5294,  ..., 0.5294, 0.5765],
          [0.6275, 0.4667,  ..., 0.4784, 0.4863],
          ...,
          [0.4353, 0.4353,  ..., 0.4392, 0.4118],
          [0.4353, 0.4078,  ..., 0.4314, 0.4353]],

         [[0.5059, 0.4824,  ..., 0.5176, 0.5686],
          [0.6078, 0.4314,  ..., 0.4667, 0.4745],
          ...,
          [0.4235, 0.4235,  ..., 0.4588, 0.4314],
          [0.4196, 0.3843,  ..., 0.4510, 0.4549]]],


        [[[0.7922, 0.7569,  ..., 0.0510, 0.0471],
          [0.7804, 0.7529,  ..., 0.0549, 0.0549],
          ...,
          [0.2941, 0.2667,  ..., 0.1412, 0.1451],
          [0.3333, 0.4039,  ..., 0.1451, 0.1490]],

         [[0.5922, 0.5451,  ..., 0.0353, 0.0314],
          [0.5922, 0.5490,  ..., 0.0431, 0.0431],
          ...,
          [0.12

In [30]:
n_channels = batch.shape[1]
for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std

In [31]:
n_channels

3

In [32]:
batch

tensor([[[[ 0.1439,  0.0730,  ...,  0.0198,  0.1794],
          [ 0.4631, -0.2461,  ..., -0.2107, -0.1752],
          ...,
          [-0.3348, -0.3171,  ..., -0.4766, -0.6007],
          [-0.3348, -0.4412,  ..., -0.4766, -0.4944]],

         [[ 0.4632,  0.3874,  ...,  0.3874,  0.6150],
          [ 0.8615,  0.0839,  ...,  0.1408,  0.1787],
          ...,
          [-0.0678, -0.0678,  ..., -0.0489, -0.1816],
          [-0.0678, -0.2006,  ..., -0.0868, -0.0678]],

         [[ 0.7792,  0.6573,  ...,  0.8401,  1.1041],
          [ 1.3072,  0.3933,  ...,  0.5761,  0.6167],
          ...,
          [ 0.3526,  0.3526,  ...,  0.5354,  0.3933],
          [ 0.3323,  0.1495,  ...,  0.4948,  0.5151]]],


        [[[ 0.9595,  0.7999,  ..., -2.3915, -2.4092],
          [ 0.9063,  0.7822,  ..., -2.3738, -2.3738],
          ...,
          [-1.2922, -1.4163,  ..., -1.9837, -1.9660],
          [-1.1149, -0.7958,  ..., -1.9660, -1.9482]],

         [[ 0.6908,  0.4632,  ..., -2.0024, -2.0214],
          [ 