In [7]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50, linewidth=75)

In [8]:
import pandas as pd

data = pd.read_csv("../data/p1ch4/bike-sharing-dataset/hour-fixed.csv")

data

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17515,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17516,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17517,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17518,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61


In [9]:
bikes_numpy = np.loadtxt(
    "../data/p1ch4/bike-sharing-dataset/hour-fixed.csv", 
    dtype=np.float32, 
    delimiter=",", 
    skiprows=1, 
    converters={1: lambda x: float(x[8:10])}) # <1>
bikes = torch.from_numpy(bikes_numpy)

bikes

tensor([[1.0000e+00, 1.0000e+00,  ..., 1.3000e+01, 1.6000e+01],
        [2.0000e+00, 1.0000e+00,  ..., 3.2000e+01, 4.0000e+01],
        ...,
        [1.7378e+04, 3.1000e+01,  ..., 4.8000e+01, 6.1000e+01],
        [1.7379e+04, 3.1000e+01,  ..., 3.7000e+01, 4.9000e+01]])

In [10]:
bikes.shape, bikes.stride()

(torch.Size([17520, 17]), (17, 1))

In [11]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1])
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 24, 17]), (408, 17, 1))

In [12]:
daily_bikes

tensor([[[1.0000e+00, 1.0000e+00,  ..., 1.3000e+01, 1.6000e+01],
         [2.0000e+00, 1.0000e+00,  ..., 3.2000e+01, 4.0000e+01],
         ...,
         [2.3000e+01, 1.0000e+00,  ..., 1.7000e+01, 2.8000e+01],
         [2.4000e+01, 1.0000e+00,  ..., 2.4000e+01, 3.9000e+01]],

        [[2.5000e+01, 2.0000e+00,  ..., 1.3000e+01, 1.7000e+01],
         [2.6000e+01, 2.0000e+00,  ..., 1.6000e+01, 1.7000e+01],
         ...,
         [4.6000e+01, 2.0000e+00,  ..., 9.0000e+00, 9.0000e+00],
         [4.7000e+01, 2.0000e+00,  ..., 8.0000e+00, 8.0000e+00]],

        ...,

        [[1.7332e+04, 3.0000e+01,  ..., 4.1000e+01, 4.1000e+01],
         [1.7333e+04, 3.0000e+01,  ..., 2.7000e+01, 2.8000e+01],
         ...,
         [1.7354e+04, 3.0000e+01,  ..., 3.0000e+01, 3.6000e+01],
         [1.7355e+04, 3.0000e+01,  ..., 3.9000e+01, 4.9000e+01]],

        [[1.7356e+04, 3.1000e+01,  ..., 3.0000e+01, 3.4000e+01],
         [1.7357e+04, 3.1000e+01,  ..., 1.3000e+01, 1.9000e+01],
         ...,
         [1.73

In [13]:
daily_bikes = daily_bikes.transpose(1, 2)
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 17, 24]), (408, 1, 17))

In [14]:
daily_bikes

tensor([[[1.0000e+00, 2.0000e+00,  ..., 2.3000e+01, 2.4000e+01],
         [1.0000e+00, 1.0000e+00,  ..., 1.0000e+00, 1.0000e+00],
         ...,
         [1.3000e+01, 3.2000e+01,  ..., 1.7000e+01, 2.4000e+01],
         [1.6000e+01, 4.0000e+01,  ..., 2.8000e+01, 3.9000e+01]],

        [[2.5000e+01, 2.6000e+01,  ..., 4.6000e+01, 4.7000e+01],
         [2.0000e+00, 2.0000e+00,  ..., 2.0000e+00, 2.0000e+00],
         ...,
         [1.3000e+01, 1.6000e+01,  ..., 9.0000e+00, 8.0000e+00],
         [1.7000e+01, 1.7000e+01,  ..., 9.0000e+00, 8.0000e+00]],

        ...,

        [[1.7332e+04, 1.7333e+04,  ..., 1.7354e+04, 1.7355e+04],
         [3.0000e+01, 3.0000e+01,  ..., 3.0000e+01, 3.0000e+01],
         ...,
         [4.1000e+01, 2.7000e+01,  ..., 3.0000e+01, 3.9000e+01],
         [4.1000e+01, 2.8000e+01,  ..., 3.6000e+01, 4.9000e+01]],

        [[1.7356e+04, 1.7357e+04,  ..., 1.7378e+04, 1.7379e+04],
         [3.1000e+01, 3.1000e+01,  ..., 3.1000e+01, 3.1000e+01],
         ...,
         [3.00

In [17]:
first_day = bikes[:24].long()
weather_onehot = torch.zeros(first_day.shape[0], 4)
print(first_day[:,9])
print(first_day)

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2,
        2, 2])
tensor([[ 1,  1,  ..., 13, 16],
        [ 2,  1,  ..., 32, 40],
        ...,
        [23,  1,  ..., 17, 28],
        [24,  1,  ..., 24, 39]])


In [18]:
weather_onehot.scatter_(
    dim=1, 
    index=first_day[:,9].unsqueeze(1).long() - 1, # <1>
    value=1.0)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        ...,
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [19]:
torch.cat((bikes[:24], weather_onehot), 1)[:1]

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  1.0000,  0.0000,  0.0000,
          6.0000,  0.0000,  1.0000,  0.2400,  0.2879,  0.8100,  0.0000,
          3.0000, 13.0000, 16.0000,  1.0000,  0.0000,  0.0000,  0.0000]])

In [20]:
daily_weather_onehot = torch.zeros(daily_bikes.shape[0], 4,
                                   daily_bikes.shape[2])
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [21]:
daily_weather_onehot.scatter_(
    1, daily_bikes[:,9,:].long().unsqueeze(1) - 1, 1.0)
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [22]:
daily_bikes = torch.cat((daily_bikes, daily_weather_onehot), dim=1)

In [23]:
daily_bikes[:, 9, :] = (daily_bikes[:, 9, :] - 1.0) / 3.0

In [24]:
temp = daily_bikes[:, 10, :]
temp_min = torch.min(temp)
temp_max = torch.max(temp)
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - temp_min)
                         / (temp_max - temp_min))

In [25]:
temp = daily_bikes[:, 10, :]
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - torch.mean(temp))
                         / torch.std(temp))